# Generated by Django 2.2.7 on 2019-11-08 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
