# Generated by Django 3.0.4 on 2020-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('utilizadores', '0003_auto_20191116_1954'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='perfil',
      name='imagem',
    ),
  ]
