# Generated by Django 3.0.3 on 2020-03-28 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utilizadores', '0004_remove_perfil_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
