# Generated by Django 2.2.7 on 2019-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myschool_app', '0009_auto_20191201_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='notas',
            field=models.TextField(blank=True, max_length=255, verbose_name='Notas'),
        ),
    ]
