# Generated by Django 2.2.7 on 2019-12-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschool_app', '0011_auto_20191201_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='teste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myschool_app.Teste'),
        ),
    ]
