# Generated by Django 2.2.7 on 2019-12-01 13:59

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('myschool_app', '0012_auto_20191201_1358'),
  ]

  operations = [
    migrations.AlterModelOptions(
      name='avaliacao',
      options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
    ),
  ]
