# Generated by Django 2.2.7 on 2019-12-03 11:00

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('myschool_app', '0013_auto_20191201_1359'),
  ]

  operations = [
    migrations.DeleteModel(
      name='Avaliacao',
    ),
  ]
