# Generated by Django 2.2.7 on 2019-12-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool_app', '0014_delete_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='realizado',
            field=models.BooleanField(blank=True, verbose_name='Realizado?'),
        ),
    ]
