# Generated by Django 2.2.7 on 2019-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('myschool_app', '0016_teste_avaliacao'),
  ]

  operations = [
    migrations.AlterField(
      model_name='teste',
      name='avaliacao',
      field=models.FloatField(blank=True, verbose_name='Avaliação'),
    ),
  ]
