# Generated by Django 2.2.7 on 2019-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('myschool_app', '0017_auto_20191203_1111'),
  ]

  operations = [
    migrations.AlterField(
      model_name='teste',
      name='avaliacao',
      field=models.FloatField(blank=True, null=True, verbose_name='Avaliação'),
    ),
    migrations.AlterField(
      model_name='teste',
      name='realizado',
      field=models.BooleanField(blank=True, null=True, verbose_name='Realizado?'),
    ),
  ]
